export const STRINGS = {
  en: {
    welcome: (name) => `Welcome! How can I assist you today?`,
    newChat: "New chat",
    agents: "Agents",
    searchChats: "Search chats",
    pickLang: "Select language",
    pickPincode: "Enter pincode",
    pickMode: "Choose assistant mode",
    start: "Start",
    emailLabel: "Work email",
    modePersonal: "Personal Assistant",
    modeGeneral: "General Assistant",
    askPlaceholder: "Ask KisanSaathi about farming, crops, weather...",
    messagePlaceholder: "Type your message…",
    askPersonalPlaceholder: "Ask Personal Assistant regarding farming, weather, market price, government policies...",
    askGeneralPlaceholder: "Ask General Assistant regarding farming, weather, market price, government policies...",
    rename: "Rename",
    delete: "Delete",
    chooseAssistants: "Choose Assistants",
    language: "Language",
    location: "Location",
    share: "Share",
    sharePublicLink: "Share public link to chat",
    sharePrivacyNotice: "Your email, personal information, and any messages you add after sharing stay private. Only the current conversation will be visible to others.",
    copyLink: "Copy link",
    linkCopied: "Link copied!",
    settings: "Settings",
    setup: "Setup",
    changePincode: "Change Pincode",
    user: "User",
    setEmail: "Set email",
    noChatsFound: "No chats found",
    searchPlaceholder: "Search your chats...",
    today: "Today",
    yesterday: "Yesterday",
    lastWeek: "Last Week",
    lastMonth: "Last Month",
    older: "Older",
    feedback: "Feedback",
    helpful: "Helpful",
    notHelpful: "Not Helpful",
    submitFeedback: "Submit Feedback",
    feedbackPlaceholder: "Tell us how we can improve...",
    cancel: "Cancel",
    submit: "Submit",
    chooseLanguage: "Choose Language (भाषा चुनें)",
    personalizedAssistant: "Personalized Assistant",
    personalizedDescription: "Get customized farming advice based on your location, crops, and specific needs",
    generalAssistant: "General Assistant", 
    generalDescription: "Get general farming information, tips, and answers to common agricultural questions",
    enterPincode: "Enter your pincode for location-based assistance",
    selectAssistantType: "Select your preferred assistant type",
    newChat: "New Chat",
    defaultChatName: "New Chat"
    
  },
  hi: {
    welcome: (name) => `स्वागत है! आज मैं आपकी कैसे सहायता कर सकता हूँ?`,
    newChat: "नई चैट",
    agents: "एजेंट्स",
    searchChats: "चैट खोजें",
    pickLang: "भाषा चुनें",
    pickPincode: "पिनकोड दर्ज करें",
    pickMode: "सहायक मोड चुनें",
    start: "शुरू करें",
    emailLabel: "कार्य ईमेल",
    modePersonal: "व्यक्तिगत सहायक",
    modeGeneral: "सामान्य सहायक",
    askPlaceholder: "किसानसाथी से खेती, फसल, मौसम के बारे में पूछें...",
    messagePlaceholder: "अपना संदेश लिखें…",
    askPersonalPlaceholder: "व्यक्तिगत सहायक से खेती, मौसम, बाजार भाव, सरकारी नीतियों के बारे में पूछें...",
    askGeneralPlaceholder: "सामान्य सहायक से खेती, मौसम, बाजार भाव, सरकारी नीतियों के बारे में पूछें...",
    rename: "नाम बदलें",
    delete: "हटाएँ",
    chooseAssistants: "सहायकों का चयन करें",
    language: "भाषा",
    location: "स्थान",
    share: "साझा करें",
    sharePublicLink: "चैट का सार्वजनिक लिंक साझा करें",
    sharePrivacyNotice: "आपका ईमेल, व्यक्तिगत जानकारी, और साझा करने के बाद आपके द्वारा जोड़े गए कोई भी संदेश निजी रहते हैं। केवल वर्तमान बातचीत दूसरों को दिखाई देगी।",
    copyLink: "लिंक कॉपी करें",
    linkCopied: "लिंक कॉपी हो गया!",
    settings: "सेटिंग्स",
    setup: "सेटअप",
    changePincode: "पिनकोड बदलें",
    user: "उपयोगकर्ता",
    setEmail: "ईमेल सेट करें",
    CHATS: "चैट्स",
    noChatsFound: "कोई चैट नहीं मिली",
    searchPlaceholder: "अपनी चैट खोजें...",
    today: "आज",
    yesterday: "कल",
    lastWeek: "पिछला सप्ताह",
    lastMonth: "पिछला महीना",
    older: "पुराना",
    feedback: "प्रतिक्रिया",
    helpful: "सहायक",
    notHelpful: "सहायक नहीं",
    submitFeedback: "प्रतिक्रिया भेजें",
    feedbackPlaceholder: "बताएं कि हम कैसे सुधार कर सकते हैं...",
    cancel: "रद्द करें",
    submit: "भेजें",
    chooseLanguage: "भाषा चुनें (Choose Language)",
    personalizedAssistant: "व्यक्तिगत सहायक",
    personalizedDescription: "अपने स्थान, फसलों और विशिष्ट आवश्यकताओं के आधार पर अनुकूलित कृषि सलाह प्राप्त करें",
    generalAssistant: "सामान्य सहायक",
    generalDescription: "सामान्य कृषि जानकारी, सुझाव और सामान्य कृषि प्रश्नों के उत्तर प्राप्त करें",
    enterPincode: "स्थान-आधारित सहायता के लिए अपना पिनकोड दर्ज करें",
    selectAssistantType: "अपना पसंदीदा सहायक प्रकार चुनें",
    defaultChatName: "नई चैट",
  },
  mr: {
    welcome: (name) => `स्वागत! आज मी तुमची कशी मदत करू शकतो?`,
    newChat: "नवी चॅट",
    agents: "एजंट्स",
    searchChats: "चॅट शोधा",
    pickLang: "भाषा निवडा",
    pickPincode: "पिनकोड टाका",
    pickMode: "सहाय्यक मोड निवडा",
    start: "सुरू करा",
    emailLabel: "कामाचा ईमेल",
    modePersonal: "वैयक्तिक सहाय्यक",
    modeGeneral: "सामान्य सहाय्यक",
    askPlaceholder: "किसानसाथी ला शेती, पीक, हवामान बद्दल विचारा...",
    messagePlaceholder: "आपला संदेश लिहा…",
    askPersonalPlaceholder: "वैयक्तिक सहाय्यकाला शेती, हवामान, बाजार भाव, सरकारी धोरणांबद्दल विचारा...",
    askGeneralPlaceholder: "सामान्य सहाय्यकाला शेती, हवामान, बाजार भाव, सरकारी धोरणांबद्दल विचारा...",
    rename: "नाव बदला",
    delete: "काढून टाका",
    chooseAssistants: "सहाय्यक निवडा",
    language: "भाषा",
    location: "ठिकाण",
    share: "शेअर करा",
    settings: "सेटिंग्स",
    setup: "सेटअप",
    changePincode: "पिनकोड बदला",
    user: "वापरकर्ता",
    setEmail: "ईमेल सेट करा",
    noChatsFound: "कोणतीही चॅट सापडली नाही",
    searchPlaceholder: "तुमची चॅट शोधा...",
    today: "आज",
    yesterday: "काल",
    lastWeek: "गेला आठवडा",
    lastMonth: "गेला महिना",
    older: "जुने",
    feedback: "अभिप्राय",
    helpful: "उपयुक्त",
    notHelpful: "उपयुक्त नाही",
    submitFeedback: "अभिप्राय पाठवा",
    feedbackPlaceholder: "आम्ही कसे सुधारू शकतो ते सांगा...",
    cancel: "रद्द करा",
    submit: "पाठवा",
    chooseLanguage: "भाषा निवडा (Choose Language)",
    personalizedAssistant: "वैयक्तिक सहाय्यक",
    personalizedDescription: "तुमच्या ठिकाणी, पिकांवर आणि विशिष्ट गरजांवर आधारित सानुकूल शेती सल्ला मिळवा",
    generalAssistant: "सामान्य सहाय्यक",
    generalDescription: "सामान्य शेती माहिती, टिप्स आणि सामान्य कृषी प्रश्नांची उत्तरे मिळवा",
    enterPincode: "स्थान-आधारित सहाय्यासाठी तुमचा पिनकोड टाका",
    selectAssistantType: "तुमचा पसंतीचा सहाय्यक प्रकार निवडा",
    defaultChatName: "नवी चॅट",
    CHATS: "चॅट्स",
  },
  gu: {
    welcome: (name) => `સ્વાગત છે! આજે હું તમારી કેવી રીતે મદદ કરી શકું?`,
    newChat: "નવી ચેટ",
    agents: "એજન્ટ્સ",
    searchChats: "ચેટ શોધો",
    pickLang: "ભાષા પસંદ કરો",
    pickPincode: "પિનકોડ દાખલ કરો",
    pickMode: "સહાયક મોડ પસંદ કરો",
    start: "શરૂ કરો",
    emailLabel: "કામનો ઈમેલ",
    modePersonal: "વ્યક્તિગત સહાયક",
    modeGeneral: "સામાન્ય સહાયક",
    askPlaceholder: "કિસાનસાથીને ખેતી, પાક, હવામાન વિશે પૂછો...",
    messagePlaceholder: "તમારો સંદેશ લખો…",
    askPersonalPlaceholder: "વ્યક્તિગત સહાયકને ખેતી, હવામાન, બજાર ભાવ, સરકારી નીતિઓ વિશે પૂછો...",
    askGeneralPlaceholder: "સામાન્ય સહાયકને ખેતી, હવામાન, બજાર ભાવ, સરકારી નીતિઓ વિશે પૂછો...",
    rename: "નામ બદલો",
    delete: "કાઢી નાખો",
    chooseAssistants: "સહાયકો પસંદ કરો",
    language: "ભાષા",
    location: "સ્થાન",
    share: "શેર કરો",
    settings: "સેટિંગ્સ",
    setup: "સેટઅપ",
    changePincode: "પિનકોડ બદલો",
    user: "વપરાશકર્તા",
    setEmail: "ઈમેલ સેટ કરો",
    noChatsFound: "કોઈ ચેટ મળી નથી",
    searchPlaceholder: "તમારી ચેટ શોધો...",
    today: "આજે",
    yesterday: "ગઈકાલે",
    lastWeek: "છેલ્લું અઠવાડિયું",
    lastMonth: "છેલ્લો મહિનો",
    older: "જૂનું",
    feedback: "પ્રતિસાદ",
    helpful: "ઉપયોગી",
    notHelpful: "ઉપયોગી નથી",
    submitFeedback: "પ્રતિસાદ મોકલો",
    feedbackPlaceholder: "અમે કેવી રીતે સુધારી શકીએ તે કહો...",
    cancel: "રદ કરો",
    submit: "મોકલો",
    chooseLanguage: "ભાષા પસંદ કરો (Choose Language)",
    personalizedAssistant: "વ્યક્તિગત સહાયક",
    personalizedDescription: "તમારા સ્થાન, પાક અને વિશિષ્ટ જરૂરિયાતોના આધારે કસ્ટમાઇઝ્ડ ખેતી સલાહ મેળવો",
    generalAssistant: "સામાન્ય સહાયક",
    generalDescription: "સામાન્ય ખેતી માહિતી, ટિપ્સ અને સામાન્ય કૃષિ પ્રશ્નોના જવાબો મેળવો",
    enterPincode: "સ્થાન-આધારિત સહાય માટે તમારો પિનકોડ દાખલ કરો",
    selectAssistantType: "તમારો પસંદીદા સહાયક પ્રકાર પસંદ કરો",
    defaultChatName: "નવી ચેટ",
    CHATS: "ચેટ્સ",
  },
  bn: {
    welcome: (name) => `স্বাগতম! আজ আমি কীভাবে আপনার সাহায্য করতে পারি?`,
    newChat: "নতুন চ্যাট",
    agents: "এজেন্টস",
    searchChats: "চ্যাট খুঁজুন",
    pickLang: "ভাষা নির্বাচন করুন",
    pickPincode: "পিনকোড লিখুন",
    pickMode: "সহকারী মোড বেছে নিন",
    start: "শুরু করুন",
    emailLabel: "কাজের ইমেল",
    modePersonal: "ব্যক্তিগত সহকারী",
    modeGeneral: "সাধারণ সহকারী",
    askPlaceholder: "কিষানসাথীকে কৃষি, ফসল, আবহাওয়া সম্পর্কে জিজ্ঞাসা করুন...",
    messagePlaceholder: "আপনার বার্তা লিখুন…",
    askPersonalPlaceholder: "ব্যক্তিগত সহকারীকে কৃষি, আবহাওয়া, বাজার দর, সরকারি নীতি সম্পর্কে জিজ্ঞাসা করুন...",
    askGeneralPlaceholder: "সাধারণ সহকারীকে কৃষি, আবহাওয়া, বাজার দর, সরকারি নীতি সম্পর্কে জিজ্ঞাসা করুন...",
    rename: "নাম পরিবর্তন করুন",
    delete: "মুছে ফেলুন",
    chooseAssistants: "সহকারী নির্বাচন করুন",
    language: "ভাষা",
    location: "অবস্থান",
    share: "শেয়ার করুন",
    settings: "সেটিংস",
    setup: "সেটআপ",
    changePincode: "পিনকোড পরিবর্তন করুন",
    user: "ব্যবহারকারী",
    setEmail: "ইমেল সেট করুন",
    noChatsFound: "কোনো চ্যাট পাওয়া যায়নি",
    searchPlaceholder: "আপনার চ্যাট খুঁজুন...",
    today: "আজ",
    yesterday: "গতকাল",
    lastWeek: "গত সপ্তাহ",
    lastMonth: "গত মাস",
    older: "পুরানো",
    feedback: "মতামত",
    helpful: "সহায়ক",
    notHelpful: "সহায়ক নয়",
    submitFeedback: "মতামত পাঠান",
    feedbackPlaceholder: "আমরা কীভাবে উন্নতি করতে পারি তা বলুন...",
    cancel: "বাতিল",
    submit: "পাঠান",
    chooseLanguage: "ভাষা নির্বাচন করুন (Choose Language)",
    personalizedAssistant: "ব্যক্তিগত সহকারী",
    personalizedDescription: "আপনার অবস্থান, ফসল এবং নির্দিষ্ট প্রয়োজনের উপর ভিত্তি করে কাস্টমাইজড কৃষি পরামর্শ পান",
    generalAssistant: "সাধারণ সহকারী",
    generalDescription: "সাধারণ কৃষি তথ্য, টিপস এবং সাধারণ কৃষি প্রশ্নের উত্তর পান",
    enterPincode: "অবস্থান-ভিত্তিক সহায়তার জন্য আপনার পিনকোড লিখুন",
    selectAssistantType: "আপনার পছন্দের সহকারী ধরন বেছে নিন",
    defaultChatName: "নতুন চ্যাট",
    CHATS: "চ্যাটস",
  },
  ta: {
    welcome: (name) => `வரவேற்கிறோம்! இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?`,
    newChat: "புதிய அரட்டை",
    agents: "முகவர்கள்",
    searchChats: "அரட்டைகளைத் தேடுங்கள்",
    pickLang: "மொழியைத் தேர்ந்தெடுக்கவும்",
    pickPincode: "பின்கோடை உள்ளிடவும்",
    pickMode: "உதவியாளர் முறையைத் தேர்ந்தெடுக்கவும்",
    start: "தொடங்கு",
    emailLabel: "வேலை மின்னஞ்சல்",
    modePersonal: "தனிப்பட்ட உதவியாளர்",
    modeGeneral: "பொது உதவியாளர்",
    askPlaceholder: "கிசான்சாத்தியிடம் விவசாயம், பயிர்கள், வானிலை பற்றி கேளுங்கள்...",
    messagePlaceholder: "உங்கள் செய்தியை தட்டச்சு செய்யுங்கள்…",
    askPersonalPlaceholder: "தனிப்பட்ட உதவியாளரிடம் விவசாயம், வானிலை, சந்தை விலை, அரசு கொள்கைகள் பற்றி கேளுங்கள்...",
    askGeneralPlaceholder: "பொது உதவியாளரிடம் விவசாயம், வானிலை, சந்தை விலை, அரசு கொள்கைகள் பற்றி கேளுங்கள்...",
    rename: "பெயர் மாற்று",
    delete: "நீக்கு",
    chooseAssistants: "உதவியாளர்களைத் தேர்ந்தெடுக்கவும்",
    language: "மொழி",
    location: "இடம்",
    share: "பகிர்",
    settings: "அமைப்புகள்",
    setup: "அமைப்பு",
    changePincode: "பின்கோடை மாற்று",
    user: "பயனர்",
    setEmail: "மின்னஞ்சலை அமைக்கவும்",
    noChatsFound: "அரட்டைகள் எதுவும் கிடைக்கவில்லை",
    searchPlaceholder: "உங்கள் அரட்டைகளைத் தேடுங்கள்...",
    today: "இன்று",
    yesterday: "நேற்று",
    lastWeek: "கடந்த வாரம்",
    lastMonth: "கடந்த மாதம்",
    older: "பழையது",
    feedback: "கருத்து",
    helpful: "உதவிகரமான",
    notHelpful: "உதவிகரமானது அல்ல",
    submitFeedback: "கருத்தை அனுப்பவும்",
    feedbackPlaceholder: "நாங்கள் எப்படி மேம்படுத்தலாம் என்று சொல்லுங்கள்...",
    cancel: "ரத்து செய்",
    submit: "அனுப்பு",
    chooseLanguage: "மொழியைத் தேர்ந்தெடுக்கவும் (Choose Language)",
    personalizedAssistant: "தனிப்பட்ட உதவியாளர்",
    personalizedDescription: "உங்கள் இடம், பயிர்கள் மற்றும் குறிப்பிட்ட தேவைகளின் அடிப்படையில் தனிப்பயனாக்கப்பட்ட விவசாய ஆலோசனையைப் பெறுங்கள்",
    generalAssistant: "பொது உதவியாளர்",
    generalDescription: "பொதுவான விவசாய தகவல்கள், குறிப்புகள் மற்றும் பொதுவான விவசாய கேள்விகளுக்கான பதில்களைப் பெறுங்கள்",
    enterPincode: "இடம் சார்ந்த உதவிக்காக உங்கள் பின்கோடை உள்ளிடவும்",
    selectAssistantType: "உங்கள் விருப்பமான உதவியாளர் வகையைத் தேர்ந்தெடுக்கவும்",
    defaultChatName: "புதிய அரட்டை",
    CHATS: "அரட்டைகள்",
  },
  te: {
    welcome: (name) => `స్వాగతం! ఈరోజు నేను మీకు ఎలా సహాయం చేయగలను?`,
    newChat: "కొత్త చాట్",
    agents: "ఏజెంట్లు",
    searchChats: "చాట్లను వెతకండి",
    pickLang: "భాషను ఎంచుకోండి",
    pickPincode: "పిన్‌కోడ్ నమోదు చేయండి",
    pickMode: "సహాయక మోడ్ ఎంచుకోండి",
    start: "ప్రారంభించండి",
    emailLabel: "పని ఇమెయిల్",
    modePersonal: "వ్యక్తిగత సహాయకుడు",
    modeGeneral: "సాధారణ సహాయకుడు",
    askPlaceholder: "కిసాన్‌సాథీని వ్యవసాయం, పంటలు, వాతావరణం గురించి అడగండి...",
    messagePlaceholder: "మీ సందేశాన్ని టైప్ చేయండి…",
    askPersonalPlaceholder: "వ్యక్తిగత సహాయకుడిని వ్యవసాయం, వాతావరణం, మార్కెట్ ధర, ప్రభుత్వ విధానాల గురించి అడగండి...",
    askGeneralPlaceholder: "సాధారణ సహాయకుడిని వ్యవసాయం, వాతావరణం, మార్కెట్ ధర, ప్రభుత్వ విధానాల గురించి అడగండి...",
    rename: "పేరు మార్చండి",
    delete: "తొలగించండి",
    chooseAssistants: "సహాయకులను ఎంచుకోండి",
    language: "భాష",
    location: "స్థానం",
    share: "షేర్ చేయండి",
    settings: "సెట్టింగ్‌లు",
    setup: "సెటప్",
    changePincode: "పిన్‌కోడ్ మార్చండి",
    user: "వినియోగదారు",
    setEmail: "ఇమెయిల్ సెట్ చేయండి",
    noChatsFound: "చాట్లు కనుగొనబడలేదు",
    searchPlaceholder: "మీ చాట్లను వెతకండి...",
    today: "ఈరోజు",
    yesterday: "నిన్న",
    lastWeek: "గత వారం",
    lastMonth: "గత నెల",
    older: "పాతవి",
    feedback: "అభిప్రాయం",
    helpful: "సహాయకరమైన",
    notHelpful: "సహాయకరం కాదు",
    submitFeedback: "అభిప్రాయం పంపండి",
    feedbackPlaceholder: "మేము ఎలా మెరుగుపరచగలమో చెప్పండి...",
    cancel: "రద్దు చేయండి",
    submit: "పంపండి",
    chooseLanguage: "భాషను ఎంచుకోండి (Choose Language)",
    personalizedAssistant: "వ్యక్తిగత సహాయకుడు",
    personalizedDescription: "మీ స్థానం, పంటలు మరియు నిర్దిష్ట అవసరాల ఆధారంగా అనుకూలీకరించిన వ్యవసాయ సలహాలను పొందండి",
    generalAssistant: "సాధారణ సహాయకుడు",
    generalDescription: "సాధారణ వ్యవసాయ సమాచారం, చిట్కాలు మరియు సాధారణ వ్యవసాయ ప్రశ్నలకు సమాధానాలను పొందండి",
    enterPincode: "స్థాన-ఆధారిత సహాయం కోసం మీ పిన్‌కోడ్‌ను నమోదు చేయండి",
    selectAssistantType: "మీ ఇష్టమైన సహాయక రకాన్ని ఎంచుకోండి",
    defaultChatName: "కొత్త చాట్",
    CHATS: "చాట్లు",
  },
  kn: {
    welcome: (name) => `ಸ್ವಾಗತ! ಇಂದು ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?`,
    newChat: "ಹೊಸ ಚಾಟ್",
    agents: "ಏಜೆಂಟ್‌ಗಳು",
    searchChats: "ಚಾಟ್‌ಗಳನ್ನು ಹುಡುಕಿ",
    pickLang: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    pickPincode: "ಪಿನ್‌ಕೋಡ್ ನಮೂದಿಸಿ",
    pickMode: "ಸಹಾಯಕ ಮೋಡ್ ಆಯ್ಕೆಮಾಡಿ",
    start: "ಪ್ರಾರಂಭಿಸಿ",
    emailLabel: "ಕೆಲಸದ ಇಮೇಲ್",
    modePersonal: "ವೈಯಕ್ತಿಕ ಸಹಾಯಕ",
    modeGeneral: "ಸಾಮಾನ್ಯ ಸಹಾಯಕ",
    askPlaceholder: "ಕಿಸಾನ್‌ಸಾಥಿಯನ್ನು ಕೃಷಿ, ಬೆಳೆಗಳು, ಹವಾಮಾನದ ಬಗ್ಗೆ ಕೇಳಿ...",
    messagePlaceholder: "ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ…",
    askPersonalPlaceholder: "ವೈಯಕ್ತಿಕ ಸಹಾಯಕನನ್ನು ಕೃಷಿ, ಹವಾಮಾನ, ಮಾರುಕಟ್ಟೆ ಬೆಲೆ, ಸರ್ಕಾರಿ ನೀತಿಗಳ ಬಗ್ಗೆ ಕೇಳಿ...",
    askGeneralPlaceholder: "ಸಾಮಾನ್ಯ ಸಹಾಯಕನನ್ನು ಕೃಷಿ, ಹವಾಮಾನ, ಮಾರುಕಟ್ಟೆ ಬೆಲೆ, ಸರ್ಕಾರಿ ನೀತಿಗಳ ಬಗ್ಗೆ ಕೇಳಿ...",
    rename: "ಹೆಸರು ಬದಲಾಯಿಸಿ",
    delete: "ಅಳಿಸಿ",
    chooseAssistants: "ಸಹಾಯಕರನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    language: "ಭಾಷೆ",
    location: "ಸ್ಥಳ",
    share: "ಹಂಚಿಕೊಳ್ಳಿ",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    setup: "ಸೆಟಪ್",
    changePincode: "ಪಿನ್‌ಕೋಡ್ ಬದಲಾಯಿಸಿ",
    user: "ಬಳಕೆದಾರ",
    setEmail: "ಇಮೇಲ್ ಸೆಟ್ ಮಾಡಿ",
    noChatsFound: "ಯಾವುದೇ ಚಾಟ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    searchPlaceholder: "ನಿಮ್ಮ ಚಾಟ್‌ಗಳನ್ನು ಹುಡುಕಿ...",
    today: "ಇಂದು",
    yesterday: "ನಿನ್ನೆ",
    lastWeek: "ಕಳೆದ ವಾರ",
    lastMonth: "ಕಳೆದ ತಿಂಗಳು",
    older: "ಹಳೆಯದು",
    feedback: "ಪ್ರತಿಕ್ರಿಯೆ",
    helpful: "ಸಹಾಯಕ",
    notHelpful: "ಸಹಾಯಕವಲ್ಲ",
    submitFeedback: "ಪ್ರತಿಕ್ರಿಯೆ ಕಳುಹಿಸಿ",
    feedbackPlaceholder: "ನಾವು ಹೇಗೆ ಸುಧಾರಿಸಬಹುದು ಎಂದು ಹೇಳಿ...",
    cancel: "ರದ್ದುಮಾಡಿ",
    submit: "ಕಳುಹಿಸಿ",
    chooseLanguage: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ (Choose Language)",
    personalizedAssistant: "ವೈಯಕ್ತಿಕ ಸಹಾಯಕ",
    personalizedDescription: "ನಿಮ್ಮ ಸ್ಥಳ, ಬೆಳೆಗಳು ಮತ್ತು ನಿರ್ದಿಷ್ಟ ಅಗತ್ಯಗಳ ಆಧಾರದ ಮೇಲೆ ಕಸ್ಟಮೈಸ್ಡ್ ಕೃಷಿ ಸಲಹೆಯನ್ನು ಪಡೆಯಿರಿ",
    generalAssistant: "ಸಾಮಾನ್ಯ ಸಹಾಯಕ",
    generalDescription: "ಸಾಮಾನ್ಯ ಕೃಷಿ ಮಾಹಿತಿ, ಸಲಹೆಗಳು ಮತ್ತು ಸಾಮಾನ್ಯ ಕೃಷಿ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ",
    enterPincode: "ಸ್ಥಳ-ಆಧಾರಿತ ಸಹಾಯಕ್ಕಾಗಿ ನಿಮ್ಮ ಪಿನ್‌ಕೋಡ್ ನಮೂದಿಸಿ",
    selectAssistantType: "ನಿಮ್ಮ ಆದ್ಯತೆಯ ಸಹಾಯಕ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    defaultChatName: "ಹೊಸ ಚಾಟ್",
    CHATS: "ಚಾಟ್‌ಗಳು",
  },
  ml: {
    welcome: (name) => `സ്വാഗതം! ഇന്ന് ഞാൻ നിങ്ങളെ എങ്ങനെ സഹായിക്കാം?`,
    newChat: "പുതിയ ചാറ്റ്",
    agents: "ഏജന്റുകൾ",
    searchChats: "ചാറ്റുകൾ തിരയുക",
    pickLang: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    pickPincode: "പിൻകോഡ് നൽകുക",
    pickMode: "സഹായക മോഡ് തിരഞ്ഞെടുക്കുക",
    start: "ആരംഭിക്കുക",
    emailLabel: "ജോലി ഇമെയിൽ",
    modePersonal: "വ്യക്തിഗത സഹായി",
    modeGeneral: "പൊതു സഹായി",
    askPlaceholder: "കിസാൻസാഥിയോട് കൃഷി, വിളകൾ, കാലാവസ്ഥ എന്നിവയെക്കുറിച്ച് ചോദിക്കുക...",
    messagePlaceholder: "നിങ്ങളുടെ സന്ദേശം ടൈപ്പ് ചെയ്യുക…",
    askPersonalPlaceholder: "വ്യക്തിഗത സഹായിയോട് കൃഷി, കാലാവസ്ഥ, വിപണി വില, സർക്കാർ നയങ്ങൾ എന്നിവയെക്കുറിച്ച് ചോദിക്കുക...",
    askGeneralPlaceholder: "പൊതു സഹായിയോട് കൃഷി, കാലാവസ്ഥ, വിപണി വില, സർക്കാർ നയങ്ങൾ എന്നിവയെക്കുറിച്ച് ചോദിക്കുക...",
    rename: "പേര് മാറ്റുക",
    delete: "ഇല്ലാതാക്കുക",
    chooseAssistants: "സഹായികളെ തിരഞ്ഞെടുക്കുക",
    language: "ഭാഷ",
    location: "സ്ഥലം",
    share: "പങ്കിടുക",
    settings: "ക്രമീകരണങ്ങൾ",
    setup: "സെറ്റപ്പ്",
    changePincode: "പിൻകോഡ് മാറ്റുക",
    user: "ഉപയോക്താവ്",
    setEmail: "ഇമെയിൽ സെറ്റ് ചെയ്യുക",
    noChatsFound: "ചാറ്റുകളൊന്നും കണ്ടെത്തിയില്ല",
    searchPlaceholder: "നിങ്ങളുടെ ചാറ്റുകൾ തിരയുക...",
    today: "ഇന്ന്",
    yesterday: "ഇന്നലെ",
    lastWeek: "കഴിഞ്ഞ ആഴ്ച",
    lastMonth: "കഴിഞ്ഞ മാസം",
    older: "പഴയത്",
    feedback: "ഫീഡ്‌ബാക്ക്",
    helpful: "സഹായകരം",
    notHelpful: "സഹായകരമല്ല",
    submitFeedback: "ഫീഡ്‌ബാക്ക് അയയ്ക്കുക",
    feedbackPlaceholder: "ഞങ്ങൾ എങ്ങനെ മെച്ചപ്പെടുത്താം എന്ന് പറയുക...",
    cancel: "റദ്ദാക്കുക",
    submit: "അയയ്ക്കുക",
    chooseLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക (Choose Language)",
    personalizedAssistant: "വ്യക്തിഗത സഹായി",
    personalizedDescription: "നിങ്ങളുടെ സ്ഥലം, വിളകൾ, പ്രത്യേക ആവശ്യങ്ങൾ എന്നിവയെ അടിസ്ഥാനമാക്കി ഇഷ്ടാനുസൃത കൃഷി ഉപദേശം നേടുക",
    generalAssistant: "പൊതു സഹായി",
    generalDescription: "പൊതുവായ കൃഷി വിവരങ്ങൾ, നുറുങ്ങുകൾ, സാധാരണ കാർഷിക ചോദ്യങ്ങൾക്കുള്ള ഉത്തരങ്ങൾ എന്നിവ നേടുക",
    enterPincode: "സ്ഥലാധിഷ്ഠിത സഹായത്തിനായി നിങ്ങളുടെ പിൻകോഡ് നൽകുക",
    selectAssistantType: "നിങ്ങളുടെ ഇഷ്ട സഹായി തരം തിരഞ്ഞെടുക്കുക",
    defaultChatName: "പുതിയ ചാറ്റ്",
    CHATS: "ചാറ്റുകൾ",
  },
  pa: {
    welcome: (name) => `ਸਵਾਗਤ ਹੈ! ਅੱਜ ਮੈਂ ਤੁਹਾਡੀ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?`,
    newChat: "ਨਵੀਂ ਚੈਟ",
    agents: "ਏਜੰਟ",
    searchChats: "ਚੈਟਾਂ ਖੋਜੋ",
    pickLang: "ਭਾਸ਼ਾ ਚੁਣੋ",
    pickPincode: "ਪਿੰਨਕੋਡ ਦਾਖਲ ਕਰੋ",
    pickMode: "ਸਹਾਇਕ ਮੋਡ ਚੁਣੋ",
    start: "ਸ਼ੁਰੂ ਕਰੋ",
    emailLabel: "ਕੰਮ ਦੀ ਈਮੇਲ",
    modePersonal: "ਨਿੱਜੀ ਸਹਾਇਕ",
    modeGeneral: "ਆਮ ਸਹਾਇਕ",
    askPlaceholder: "ਕਿਸਾਨਸਾਥੀ ਨੂੰ ਖੇਤੀ, ਫਸਲਾਂ, ਮੌਸਮ ਬਾਰੇ ਪੁੱਛੋ...",
    messagePlaceholder: "ਆਪਣਾ ਸੰਦੇਸ਼ ਟਾਈਪ ਕਰੋ…",
    askPersonalPlaceholder: "ਨਿੱਜੀ ਸਹਾਇਕ ਨੂੰ ਖੇਤੀ, ਮੌਸਮ, ਮਾਰਕੀਟ ਰੇਟ, ਸਰਕਾਰੀ ਨੀਤੀਆਂ ਬਾਰੇ ਪੁੱਛੋ...",
    askGeneralPlaceholder: "ਆਮ ਸਹਾਇਕ ਨੂੰ ਖੇਤੀ, ਮੌਸਮ, ਮਾਰਕੀਟ ਰੇਟ, ਸਰਕਾਰੀ ਨੀਤੀਆਂ ਬਾਰੇ ਪੁੱਛੋ...",
    rename: "ਨਾਮ ਬਦਲੋ",
    delete: "ਮਿਟਾਓ",
    chooseAssistants: "ਸਹਾਇਕ ਚੁਣੋ",
    language: "ਭਾਸ਼ਾ",
    location: "ਸਥਾਨ",
    share: "ਸਾਂਝਾ ਕਰੋ",
    settings: "ਸੈਟਿੰਗਾਂ",
    setup: "ਸੈਟਅਪ",
    changePincode: "ਪਿੰਨਕੋਡ ਬਦਲੋ",
    user: "ਵਰਤੋਂਕਾਰ",
    setEmail: "ਈਮੇਲ ਸੈਟ ਕਰੋ",
    noChatsFound: "ਕੋਈ ਚੈਟ ਨਹੀਂ ਮਿਲੀ",
    searchPlaceholder: "ਆਪਣੀਆਂ ਚੈਟਾਂ ਖੋਜੋ...",
    today: "ਅੱਜ",
    yesterday: "ਕੱਲ੍ਹ",
    lastWeek: "ਪਿਛਲਾ ਹਫ਼ਤਾ",
    lastMonth: "ਪਿਛਲਾ ਮਹੀਨਾ",
    older: "ਪੁਰਾਣਾ",
    feedback: "ਫੀਡਬੈਕ",
    helpful: "ਮਦਦਗਾਰ",
    notHelpful: "ਮਦਦਗਾਰ ਨਹੀਂ",
    submitFeedback: "ਫੀਡਬੈਕ ਭੇਜੋ",
    feedbackPlaceholder: "ਦੱਸੋ ਕਿ ਅਸੀਂ ਕਿਵੇਂ ਸੁਧਾਰ ਕਰ ਸਕਦੇ ਹਾਂ...",
    cancel: "ਰੱਦ ਕਰੋ",
    submit: "ਭੇਜੋ",
    chooseLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ (Choose Language)",
    personalizedAssistant: "ਨਿੱਜੀ ਸਹਾਇਕ",
    personalizedDescription: "ਆਪਣੇ ਸਥਾਨ, ਫਸਲਾਂ ਅਤੇ ਖਾਸ ਲੋੜਾਂ ਦੇ ਆਧਾਰ 'ਤੇ ਕਸਟਮਾਈਜ਼ਡ ਖੇਤੀ ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ",
    generalAssistant: "ਆਮ ਸਹਾਇਕ",
    generalDescription: "ਆਮ ਖੇਤੀ ਜਾਣਕਾਰੀ, ਸੁਝਾਅ ਅਤੇ ਆਮ ਖੇਤੀ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਪ੍ਰਾਪਤ ਕਰੋ",
    enterPincode: "ਸਥਾਨ-ਆਧਾਰਿਤ ਸਹਾਇਤਾ ਲਈ ਆਪਣਾ ਪਿੰਨਕੋਡ ਦਾਖਲ ਕਰੋ",
    selectAssistantType: "ਆਪਣਾ ਪਸੰਦੀਦਾ ਸਹਾਇਕ ਕਿਸਮ ਚੁਣੋ",
    defaultChatName: "ਨਵੀਂ ਚੈਟ",
    CHATS: "ਚੈਟਾਂ",
  },
  or: {
    welcome: (name) => `ସ୍ୱାଗତ! ଆଜି ମୁଁ ଆପଣଙ୍କୁ କିପରି ସାହାଯ୍ୟ କରିପାରିବି?`,
    newChat: "ନୂଆ ଚାଟ୍",
    agents: "ଏଜେଣ୍ଟମାନେ",
    searchChats: "ଚାଟ୍ ଖୋଜନ୍ତୁ",
    pickLang: "ଭାଷା ବାଛନ୍ତୁ",
    pickPincode: "ପିନକୋଡ୍ ପ୍ରବେଶ କରନ୍ତୁ",
    pickMode: "ସହାୟକ ମୋଡ୍ ବାଛନ୍ତୁ",
    start: "ଆରମ୍ଭ କରନ୍ତୁ",
    emailLabel: "କାର୍ଯ୍ୟ ଇମେଲ୍",
    modePersonal: "ବ୍ୟକ୍ତିଗତ ସହାୟକ",
    modeGeneral: "ସାଧାରଣ ସହାୟକ",
    askPlaceholder: "କିସାନସାଥୀଙ୍କୁ କୃଷି, ଫସଲ, ପାଗ ବିଷୟରେ ପଚାରନ୍ତୁ...",
    messagePlaceholder: "ଆପଣଙ୍କ ବାର୍ତ୍ତା ଟାଇପ୍ କରନ୍ତୁ…",
    askPersonalPlaceholder: "ବ୍ୟକ୍ତିଗତ ସହାୟକଙ୍କୁ କୃଷି, ପାଗ, ବଜାର ଦର, ସରକାରୀ ନୀତି ବିଷୟରେ ପଚାରନ୍ତୁ...",
    askGeneralPlaceholder: "ସାଧାରଣ ସହାୟକଙ୍କୁ କୃଷି, ପାଗ, ବଜାର ଦର, ସରକାରୀ ନୀତି ବିଷୟରେ ପଚାରନ୍ତୁ...",
    rename: "ନାମ ବଦଳାନ୍ତୁ",
    delete: "ଡିଲିଟ୍ କରନ୍ତୁ",
    chooseAssistants: "ସହାୟକମାନଙ୍କୁ ବାଛନ୍ତୁ",
    language: "ଭାଷା",
    location: "ସ୍ଥାନ",
    share: "ସେୟାର୍ କରନ୍ତୁ",
    settings: "ସେଟିଂସ୍",
    setup: "ସେଟଅପ୍",
    changePincode: "ପିନକୋଡ୍ ବଦଳାନ୍ତୁ",
    user: "ବ୍ୟବହାରକାରୀ",
    setEmail: "ଇମେଲ୍ ସେଟ୍ କରନ୍ତୁ",
    noChatsFound: "କୌଣସି ଚାଟ୍ ମିଳିଲା ନାହିଁ",
    searchPlaceholder: "ଆପଣଙ୍କ ଚାଟ୍ ଖୋଜନ୍ତୁ...",
    today: "ଆଜି",
    yesterday: "ଗତକାଲି",
    lastWeek: "ଗତ ସପ୍ତାହ",
    lastMonth: "ଗତ ମାସ",
    older: "ପୁରୁଣା",
    feedback: "ମତାମତ",
    helpful: "ସହାୟକ",
    notHelpful: "ସହାୟକ ନୁହେଁ",
    submitFeedback: "ମତାମତ ପଠାନ୍ତୁ",
    feedbackPlaceholder: "ଆମେ କିପରି ଉନ୍ନତି କରିପାରିବା କୁହନ୍ତୁ...",
    cancel: "ବାତିଲ୍ କରନ୍ତୁ",
    submit: "ପଠାନ୍ତୁ",
    chooseLanguage: "ଭାଷା ବାଛନ୍ତୁ (Choose Language)",
    personalizedAssistant: "ବ୍ୟକ୍ତିଗତ ସହାୟକ",
    personalizedDescription: "ଆପଣଙ୍କ ସ୍ଥାନ, ଫସଲ ଏବଂ ନିର୍ଦ୍ଦିଷ୍ଟ ଆବଶ୍ୟକତା ଆଧାରରେ କଷ୍ଟମାଇଜ୍ଡ କୃଷି ପରାମର୍ଶ ପାଆନ୍ତୁ",
    generalAssistant: "ସାଧାରଣ ସହାୟକ",
    generalDescription: "ସାଧାରଣ କୃଷି ସୂଚନା, ଟିପ୍ସ ଏବଂ ସାଧାରଣ କୃଷି ପ୍ରଶ୍ନର ଉତ୍ତର ପାଆନ୍ତୁ",
    enterPincode: "ସ୍ଥାନ-ଆଧାରିତ ସହାୟତା ପାଇଁ ଆପଣଙ୍କ ପିନକୋଡ୍ ପ୍ରବେଶ କରନ୍ତୁ",
    selectAssistantType: "ଆପଣଙ୍କ ପସନ୍ଦର ସହାୟକ ପ୍ରକାର ବାଛନ୍ତୁ",
    defaultChatName: "ନୂଆ ଚାଟ୍",
    CHATS: "ଚାଟ୍‌ଗୁଡ଼ିକ",
  },
  as: {
    welcome: (name) => `স্বাগতম! আজি মই আপোনাক কেনেকৈ সহায় কৰিব পাৰোঁ?`,
    newChat: "নতুন চেট",
    agents: "এজেণ্টসকল",
    searchChats: "চেট বিচাৰক",
    pickLang: "ভাষা বাছনি কৰক",
    pickPincode: "পিনক'ড দিয়ক",
    pickMode: "সহায়ক ম'ড বাছনি কৰক",
    start: "আৰম্ভ কৰক",
    emailLabel: "কামৰ ইমেইল",
    modePersonal: "ব্যক্তিগত সহায়ক",
    modeGeneral: "সাধাৰণ সহায়ক",
    askPlaceholder: "কিষাণসাথীক কৃষি, শস্য, বতৰৰ বিষয়ে সোধক...",
    messagePlaceholder: "আপোনাৰ বাৰ্তা টাইপ কৰক…",
    askPersonalPlaceholder: "ব্যক্তিগত সহায়কক কৃষি, বতৰ, বজাৰৰ দাম, চৰকাৰী নীতিৰ বিষয়ে সোধক...",
    askGeneralPlaceholder: "সাধাৰণ সহায়কক কৃষি, বতৰ, বজাৰৰ দাম, চৰকাৰী নীতিৰ বিষয়ে সোধক...",
    rename: "নাম সলনি কৰক",
    delete: "মচি পেলাওক",
    chooseAssistants: "সহায়কসকল বাছনি কৰক",
    language: "ভাষা",
    location: "স্থান",
    share: "শ্বেয়াৰ কৰক",
    settings: "ছেটিংছ",
    setup: "ছেটআপ",
    changePincode: "পিনক'ড সলনি কৰক",
    user: "ব্যৱহাৰকাৰী",
    setEmail: "ইমেইল ছেট কৰক",
    noChatsFound: "কোনো চেট পোৱা নগ'ল",
    searchPlaceholder: "আপোনাৰ চেট বিচাৰক...",
    today: "আজি",
    yesterday: "কালি",
    lastWeek: "যোৱা সপ্তাহ",
    lastMonth: "যোৱা মাহ",
    older: "পুৰণা",
    feedback: "মতামত",
    helpful: "সহায়ক",
    notHelpful: "সহায়ক নহয়",
    submitFeedback: "মতামত পঠিয়াওক",
    feedbackPlaceholder: "আমি কেনেকৈ উন্নতি কৰিব পাৰোঁ কওক...",
    cancel: "বাতিল কৰক",
    submit: "পঠিয়াওক",
    chooseLanguage: "ভাষা বাছনি কৰক (Choose Language)",
    personalizedAssistant: "ব্যক্তিগত সহায়ক",
    personalizedDescription: "আপোনাৰ স্থান, শস্য আৰু বিশেষ প্ৰয়োজনৰ ভিত্তিত কাষ্টমাইজড কৃষি পৰামৰ্শ লাভ কৰক",
    generalAssistant: "সাধাৰণ সহায়ক",
    generalDescription: "সাধাৰণ কৃষি তথ্য, টিপছ আৰু সাধাৰণ কৃষি প্ৰশ্নৰ উত্তৰ লাভ কৰক",
    enterPincode: "স্থান-ভিত্তিক সহায়ৰ বাবে আপোনাৰ পিনক'ড দিয়ক",
    selectAssistantType: "আপোনাৰ পছন্দৰ সহায়ক প্ৰকাৰ বাছনি কৰক",
    defaultChatName: "নতুন চেট",
    CHATS: "চেটসমূহ",
  },
};

export const GREETINGS = [
  "How can I help today?",
  "What would you like to do?",
  "Ready to get started?",
  "Ask me anything.",
  "What's on your mind?",
  "What can I do for you?",
  "I'm here to help.",
  "What brings you here today?",
  "Let's get things done.",
  "Need ideas or guidance?",
  "What task should we tackle?",
  "Have a question?",
  "Tell me your goal.",
  "Want to plan something?",
  "Looking up information?",
  "Need a recommendation?",
  "Want to analyze data?",
  "Curious about the weather?",
  "How can I assist you?",
];